artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dir: C:\Users\OMEN\Malaria_Project\notebook\data
  local_data_file: artifacts/data_ingestion/malaria_data.zip
  unzip_dir: artifacts/data_ingestion/malaria_dataset